# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockupConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='nombre')),
                ('url', models.URLField(verbose_name='url')),
                ('method', models.CharField(choices=[(b'GET', b'GET'), (b'POST', b'POST'), (b'PUT', b'PUT'), (b'PATH', b'PATH'), (b'DELETE', b'DELET')], max_length=1024, verbose_name='metodo http')),
                ('url_param', jsonfield.fields.JSONField(verbose_name='par\xe1metros por url')),
                ('get_param', jsonfield.fields.JSONField(verbose_name='par\xe1metros get')),
                ('post_body_param', jsonfield.fields.JSONField(verbose_name='par\xe1metros post')),
                ('mockup_content', jsonfield.fields.JSONField(verbose_name='contenido')),
            ],
        ),
    ]
