# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockupconfig',
            old_name='mockup_content',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='mockupconfig',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='url'),
        ),
    ]
