# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 16:41
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0002_auto_20171007_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockupconfig',
            name='content',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='mockupconfig',
            name='get_param',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='par\xe1metros get'),
        ),
        migrations.AlterField(
            model_name='mockupconfig',
            name='post_body_param',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='par\xe1metros post'),
        ),
        migrations.AlterField(
            model_name='mockupconfig',
            name='url_param',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='par\xe1metros por url'),
        ),
    ]
